# Generated by Django 4.2 on 2023-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='AboutUs text')),
                ('experience', models.PositiveIntegerField(verbose_name='AboutUs experience')),
                ('chef', models.PositiveIntegerField(verbose_name='AboutUs chef')),
                ('img1', models.ImageField(upload_to='about_images', verbose_name='AboutUs image1')),
                ('img2', models.ImageField(upload_to='about_images', verbose_name='AboutUs image2')),
                ('img3', models.ImageField(upload_to='about_images', verbose_name='AboutUs image3')),
                ('img4', models.ImageField(upload_to='about_images', verbose_name='AboutUs image4')),
            ],
        ),
    ]
