# Generated by Django 4.2 on 2023-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='MenuFood name')),
                ('about', models.TextField(verbose_name='MenuFood about')),
                ('img', models.ImageField(upload_to='menu_images', verbose_name='MenuFood image')),
                ('price', models.PositiveIntegerField(verbose_name='MenuFood price')),
            ],
        ),
    ]
