# Generated by Django 4.2 on 2023-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menufood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book user name')),
                ('email', models.EmailField(max_length=254, verbose_name='Book user email')),
                ('date_time', models.DateField(verbose_name='Book user date time')),
                ('count_people', models.PositiveIntegerField(verbose_name='Book people count')),
                ('subject', models.TextField(verbose_name='Book subject')),
            ],
        ),
    ]
