# Generated by Django 4.2 on 2023-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_time',
            field=models.CharField(max_length=100, verbose_name='Book user date time'),
        ),
    ]
